In [1]:
import numpy as np
import tensorflow as tf
from tensorflow.python.framework import ops
ops.reset_default_graph()

In [2]:
sess = tf.Session()

In [4]:
#Declaring Matrices
identity_matrix = tf.diag(diagonal=[1.0,1.0,1.0])
print(sess.run(identity_matrix))

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


In [5]:
A = tf.truncated_normal([2,3])
print(sess.run(A))

[[-0.35618573  0.46137977  0.49746865]
 [ 0.48988524  0.88396597  1.22639322]]


In [6]:
B = tf.fill([2,3],5.0)
print(sess.run(B))

[[ 5.  5.  5.]
 [ 5.  5.  5.]]


In [7]:
C = tf.random_uniform([3,2])
print(sess.run(C))

[[ 0.9468112   0.31124568]
 [ 0.17145848  0.98778045]
 [ 0.06861043  0.47810769]]


In [8]:
#Create matrix from np arr:
D = tf.convert_to_tensor(np.array([[1., 2., 3.], [-3., -7., -1.], [0., 5., -2.]]))
print(sess.run(D))

[[ 1.  2.  3.]
 [-3. -7. -1.]
 [ 0.  5. -2.]]


### Matrix Op

In [9]:
print(sess.run(A+B))

[[ 5.74108601  3.90102053  4.6733923 ]
 [ 4.68437004  3.19312882  5.96509171]]


In [10]:
print(sess.run(B-B))

[[ 0.  0.  0.]
 [ 0.  0.  0.]]


In [11]:
print(sess.run(tf.matmul(B,identity_matrix)))

[[ 5.  5.  5.]
 [ 5.  5.  5.]]


In [12]:
print(sess.run(tf.transpose(C)))

[[ 0.93271577  0.74152827  0.80237222]
 [ 0.14282918  0.63234425  0.56043768]]


In [13]:
print(sess.run(tf.matrix_determinant(D)))

-38.0


In [14]:
print(sess.run(tf.matrix_inverse(D)))

[[-0.5        -0.5        -0.5       ]
 [ 0.15789474  0.05263158  0.21052632]
 [ 0.39473684  0.13157895  0.02631579]]


In [15]:
print(sess.run(tf.cholesky(identity_matrix)))

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


Eigenvalues and Eigenvectors:  We use `tf.self_adjoint_eig()` function, which returns two objects, first one is an array of eigenvalues, the second is a matrix of the eigenvectors.

In [16]:
eigenvalues, eigenvectors = sess.run(tf.self_adjoint_eig(D))
print(eigenvalues)
print(eigenvectors)

[-10.65907521  -0.22750691   2.88658212]
[[ 0.21749542  0.63250104 -0.74339638]
 [ 0.84526515  0.2587998   0.46749277]
 [-0.4880805   0.73004459  0.47834331]]
