In [1]:
import tensorflow as tf

In [2]:
hello = tf.constant("Hello ")

In [3]:
world = tf.constant("World ")

In [4]:
type(hello)

tensorflow.python.framework.ops.Tensor

In [5]:
print(hello)

Tensor("Const:0", shape=(), dtype=string)


In [6]:
with tf.Session() as sess:
    result = sess.run(hello+world)

In [7]:
print(result)

b'Hello World '


In [8]:
a = tf.constant(10)
b = tf.constant(20)

In [9]:
a + b

<tf.Tensor 'add_1:0' shape=() dtype=int32>

In [10]:
with tf.Session() as sess:
    result = sess.run(a+b)

In [11]:
result

30

In [19]:
const = tf.constant(10)

In [20]:
fill_mat = tf.fill((4,4),10)

In [21]:
myzeros = tf.zeros((4,4))

In [22]:
myones = tf.ones((4,4))

In [23]:
myrandn = tf.random_normal((4,4),mean=0,stddev=1.0)   #random districution

In [24]:
myrandu = tf.random_uniform((4,4),minval=0,maxval=1) #uniform districution

In [25]:
myzeros

<tf.Tensor 'zeros_1:0' shape=(4, 4) dtype=float32>

In [27]:
my_operations = [const,fill_mat,myzeros,myones,myrandn,myrandu]

In [28]:
sess = tf.InteractiveSession()

In [35]:
for opr in my_operations:
    
#     print(sess.run(opr),"\n*****")
    print(opr.eval(),"\n******")   #evaluation same as above one 

10 
******
[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]] 
******
[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]] 
******
[[ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]] 
******
[[-1.85544455  0.42603341 -1.08401585  0.23158164]
 [ 0.72569931  0.70383418 -0.67657548  0.26333171]
 [ 1.59033871 -0.17672336  0.73602241 -0.48005846]
 [ 1.92217267 -0.21320878  0.60373038  0.60786861]] 
******
[[ 0.24935031  0.59062874  0.42510021  0.47217512]
 [ 0.7486279   0.93503392  0.64637721  0.32307482]
 [ 0.8146348   0.4256196   0.44305325  0.43314505]
 [ 0.35941195  0.59585881  0.75736535  0.83079457]] 
******


In [42]:
a = tf.constant([[1,2],
                [3,4]])

In [43]:
a.get_shape()

TensorShape([Dimension(2), Dimension(2)])

In [44]:
b = tf.constant([[10],
                [100]])

In [45]:
b.get_shape()

TensorShape([Dimension(2), Dimension(1)])

In [47]:
result = tf.matmul(a,b)
#Here we use - sess = tf.InteractiveSession()
sess.run(result)

array([[210],
       [430]], dtype=int32)

In [52]:
result.eval()

array([[210],
       [430]], dtype=int32)